### ISSUE TITLE
Línea 69

### ISSUE THREAD

**Issue by ualkman** [AscendG630-DEV/android_device_huawei_g630#3]
Me extraña un poco ver 'on boot' dos veces en la misma línea en ramdisk/init.qcom.rc, tampoco entiendo mucho, si es así ignora esto

**Comment by ualkman** [comment]
te pido algo de ayuda en esto, me gustaría terminar lo que empezaste

**Comment by EloYGomeZ** [comment]
Es un error de escritura no afecta en nada al rendimiento ya que la funciona la realiza correctamente...

**Comment by ualkman** [comment]
No sabia, gracias por aclarar.. Para arreglar el WiFi, que decías que
fallaba? En cuanto encuentre un móvil para usar en vez del G630 me pongo a
intentar debuggearlo, si puedes ayudarme en algo te lo agradeceria

**Comment by EloYGomeZ** [comment]
Amigo sin terminal en mi poder no puedo decirte mucho mas el wifi ves probando configuraciones de las repos o con los logcat ves viendo el error
